name: AwakenSMPOnline
version: '${project.version}'
main: me.efekos.awakensmponline.Main
api-version: 1.20
authors: [ efekos ]
description: AwakenSMP System with advanced features
website: https://www.spigotmc.org/resources/awakensmp-online.102573/
author: efekos
softdepend:
  - PlaceholderAPI
permissions:
  awakensmp.deadplayers:
    description: Allows you to use /awakensmp deadplayers
  awakensmp.kill-command:
    description: Allows you to use /awakensmp kill
  awakensmp.reloadconfig:
    description: Allows you to use /awakensmp reloadconfig
  awakensmp.revive:
    description: Allows you to use /awakensmp revive
  awakensmp.admin:
    description: Allows you to use every command under /awakensmp
    children:
      - awakensmp.deadplayers
      - awakensmp.kill
      - awakensmp.reloadconfig
      - awakensmp.revive
  awakensmp.friend.accept:
    description: Allows you to use /friend accept
    default: true
  awakensmp.friend.add:
    description: Allows you to use /friend add
    default: true
  awakensmp.friend.armor:
    description: Allows you to use /friend armor
    default: true
  awakensmp.friend.cancel:
    description: Allows you to use /friend cancel
    default: true
  awakensmp.friend.compass:
    description: Allows you to use /friend compass
    default: true
  awakensmp.friend.deny:
    description: Allows you to use /friend deny
    default: true
  awakensmp.friend.info:
    description: Allows you to use /friend info
    default: true
  awakensmp.friend.inventory:
    description: Allows you to use /friend inventory
    default: true
  awakensmp.friend.list:
    description: Allows you to use /friend list
    default: true
  awakensmp.friend.modify:
    description: Allows you to use /friend modify
    default: true
  awakensmp.friend.remove:
    description: Allows you to use /friend remove
    default: true
  awakensmp.friend.teleport:
    description: Allows you to use /friend teleport
    default: true
  awakensmp.friend.*:
    description: Allows you to use every command under /friend
    default: true
    children:
      - awakensmp.friend.accept
      - awakensmp.friend.add
      - awakensmp.friend.armor
      - awakensmp.friend.cancel
      - awakensmp.friend.compass
      - awakensmp.friend.deny
      - awakensmp.friend.info
      - awakensmp.friend.inventory
      - awakensmp.friend.list
      - awakensmp.friend.modify
      - awakensmp.friend.remove
      - awakensmp.friend.teleport
  awakensmp.team.chat:
    description: Allows you to use /team chat
    default: true
  awakensmp.team.create:
    description: Allows you to use /team create
    default: true
  awakensmp.team.delete:
    description: Allows you to use /team delete
    default: true
  awakensmp.team.join:
    description: Allows you to use /team join
    default: true
  awakensmp.team.leave:
    description: Allows you to use /team leave
    default: true
  awakensmp.team.members:
    description: Allows you to use /team members
    default: true
  awakensmp.team.my:
    description: Allows you to use /team my
    default: true
  awakensmp.team.reject:
    description: Allows you to use /team reject
    default: true
  awakensmp.team.togglechat:
    description: Allows you to use /team togglechat
    default: true
  awakensmp.team.*:
    default: true
    description: Allows you to use every command under /team
    children:
      - awakensmp.team.chat
      - awakensmp.team.create
      - awakensmp.team.delete
      - awakensmp.team.join
      - awakensmp.team.leave
      - awakensmp.team.members
      - awakensmp.team.my
      - awakensmp.team.reject
      - awakensmp.team.togglechat
  awakensmp.kill:
    description: Allows you to kill someone
    default: true
  awakensmp.god:
    description: Makes you invulnerable to actually die. You just respawn.
  awakensmp.*:
    description: Gives you everything
    default: op
    children:
      - awakensmp.friend.*
      - awakensmp.team.*
      - awakensmp.kill
      - awakensmp.god
      - awakensmp.admin